language: node_js
node_js:
    - 12.13.0
dist: bionic
cache:
    directories:
        - "$HOME/.cache"
env:
    - PORT=8081
before_install:
    - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
install:
    - yarn install --frozen-lockfile
    - yarn localize
    - yarn test
    - yarn start &
script:
    - yarn wait-on http-get://localhost:8081
after_script:
    - kill $(jobs -p) || true
addons:
    apt:
        packages:
            - libgconf-2-4
